version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-rss}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-rss}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEBHOOK_URL: ${WEBHOOK_URL}
      POLL_INTERVAL: ${POLL_INTERVAL:-300}
    volumes:
      - ./app:/app
    command: python -u /app/main.py

volumes:
  db_data: