version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rss_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rss_password}
      POSTGRES_DB: ${POSTGRES_DB:-rss_db}
    ports:
      - '7980:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-rss_user}:${POSTGRES_PASSWORD:-rss_password}@db:5432/${POSTGRES_DB:-rss_db}
      OPENAI_API_KEY: ABC # ${OPENAI_API_KEY}
      WEBHOOK_URL: ${WEBHOOK_URL}
      POLL_INTERVAL: ${POLL_INTERVAL:-300}
      API_PORT: ${API_PORT:-8000}
      MODEL_NAME: ${MODEL_NAME:-gpt-4.1}
      MODEL_TEMPERATURE: ${MODEL_TEMPERATURE:-0.5}
      MODEL_MAX_TOKENS: ${MODEL_MAX_TOKENS:-150}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    volumes:
      - ./app:/app/app
    command: python -u -m app.main

volumes:
  db_data: