services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rss_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rss_password}
      POSTGRES_DB: ${POSTGRES_DB:-rss_db}
      TZ: America/New_York
    ports:
      - '7980:5432'
    volumes:
      - ./.data/:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-rss_user}:${POSTGRES_PASSWORD:-rss_password}@db:5432/${POSTGRES_DB:-rss_db}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      WEBHOOK_URL: ${WEBHOOK_URL}
      POLL_INTERVAL: ${POLL_INTERVAL:-300}
      SUMMARIZE_INTERVAL: ${SUMMARIZE_INTERVAL:-300}
      DISPATCH_INTERVAL: ${DISPATCH_INTERVAL:-3600}
      PLUGIN_INTERVAL: ${PLUGIN_INTERVAL:-86400}
      API_PORT: ${API_PORT:-8000}
      TZ: America/New_York
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    volumes:
      - /run
    command: uvicorn main:app --host 0.0.0.0 --port ${API_PORT:-8000}

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    environment:
      UI_PORT: ${UI_PORT:-7860}
      API_PORT: ${API_PORT:-8000}
      API_BASE: http://backend:${API_PORT:-8000}/api
      TZ: America/New_York
    ports:
      - "${UI_PORT:-7860}:${UI_PORT:-7860}"
    volumes:
      - /run
    command: python ui_main.py

volumes:
  db_data: