# RSS feeds configuration
# Define the list of feeds to monitor and the global polling interval (in seconds).
feeds:
  - name: ExampleFeed
    url: https://example.com/rss
# polling interval for checking feeds (defaults to environment variable POLL_INTERVAL or 300 seconds)
interval: 300
