# List of users and their interest filters
# Example:
# - username: alice
#   webhook: https://your.webhook/for/alice
#   interests:
#     - "AI"
#     - "OpenAI"
# - username: bob
#   webhook: https://bob.webhook/notify
#   interests:
#     - "cloud"
#     - "python"
users:
  - username: Jie
    webhook: http://localhost:10086/webhooks/flows/88d37d5a-0b83-454c-9514-126be1648a11/sync
    interests:
      - "AI"
      - "OpenAI"